name = "Cave Game"
author = "ilGuappo"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3f55f74f5d5f0d75e90f6bb5631e0feca2a2f1440d8d3e267cc5a5577220567f"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
