name = "Cave Game"
author = "ilGuappo"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95e55f44f9315255d40ae3036f4f0df4c28aaf92c8566c8baf2990c223f30114"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
