name = "Cave Game"
author = "ilGuappo"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5994e98e8bec86c2f90279b0de77b1dc436b44cbc44a5b47481b49bbf1936d09"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
