name = "Cave Game"
author = "ilGuappo"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4be81361ba8d3beb0f915df06606feb017e1495ef8c61954ee43304f49c48f34"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
