name = "cave_game"
author = "ilGuappo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2fe53817889e09b11c8fe70e8b51481da231bec89d3ae71e66d0c9f7b608f687"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.133"
