name = "Cave Game"
author = "ilGuappo"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d73d88b8bad809975ce1b29c812ffc0843cc32f046d91fdf3b28607342ef60e"

[versions]
fabric = "0.18.3"
minecraft = "1.20.1"
