name = "Cave Game"
author = "ilGuappo"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aaa612e5e3f567f2ae4867d0313fc8cafb2eadd85fa7c02e51ae2a6b329baad8"

[versions]
fabric = "0.18.3"
minecraft = "1.20.1"
